app: test-app-tenant1
env: prod-crst
namespace: default
chart:
  repository: https://chart.onechart.dev
  name: onechart
  version: 0.41.0
values:
  gitRepository: laszlocph/test-app
  gitSha: '{{ .SHA }}'
strategicMergePatches: ""
json6902Patches: []
manifests: ""
